# https://gohugo.io/getting-started/configuration/

# URL handling.
baseURL = "https://periph.io/"
canonifyurls = false

disableKinds = ["RSS"]

[markup]
  [markup.highlight]
    codeFences = true
    useClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  image = "https://periph.io/img/periph-mascot-fb.png"
